//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevelUp.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LevelUp.Mobile.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate plan.
        /// </summary>
        internal static string ActivatePlan {
            get {
                return ResourceManager.GetString("ActivatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exercise.
        /// </summary>
        internal static string AddExercise {
            get {
                return ResourceManager.GetString("AddExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exercises.
        /// </summary>
        internal static string AddExercises {
            get {
                return ResourceManager.GetString("AddExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the button below to add exercises to this day.
        /// </summary>
        internal static string AddFirstExercise {
            get {
                return ResourceManager.GetString("AddFirstExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track. Progress. Dominate..
        /// </summary>
        internal static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Metrics.
        /// </summary>
        internal static string AvailableMetrics {
            get {
                return ResourceManager.GetString("AvailableMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyweight.
        /// </summary>
        internal static string Bodyweight {
            get {
                return ResourceManager.GetString("Bodyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string BodyweightFactor {
            get {
                return ResourceManager.GetString("BodyweightFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyweight Info.
        /// </summary>
        internal static string BodyweightInfo {
            get {
                return ResourceManager.GetString("BodyweightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        internal static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Mistakes.
        /// </summary>
        internal static string CommonMistakes {
            get {
                return ResourceManager.GetString("CommonMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure plan.
        /// </summary>
        internal static string ConfigurePlan {
            get {
                return ResourceManager.GetString("ConfigurePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Google.
        /// </summary>
        internal static string ContinueWithGoogle {
            get {
                return ResourceManager.GetString("ContinueWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first weekly plan.
        /// </summary>
        internal static string CreateFirstPlan {
            get {
                return ResourceManager.GetString("CreateFirstPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create plan.
        /// </summary>
        internal static string CreatePlan {
            get {
                return ResourceManager.GetString("CreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger zone.
        /// </summary>
        internal static string DangerZone {
            get {
                return ResourceManager.GetString("DangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string DayFri {
            get {
                return ResourceManager.GetString("DayFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string DayFriFull {
            get {
                return ResourceManager.GetString("DayFriFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string DayMon {
            get {
                return ResourceManager.GetString("DayMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string DayMonFull {
            get {
                return ResourceManager.GetString("DayMonFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day notes (optional).
        /// </summary>
        internal static string DayNotesLabel {
            get {
                return ResourceManager.GetString("DayNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. Strength, light cardio….
        /// </summary>
        internal static string DayNotesPlaceholder {
            get {
                return ResourceManager.GetString("DayNotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note for this day.
        /// </summary>
        internal static string DayNotesSub {
            get {
                return ResourceManager.GetString("DayNotesSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Notes.
        /// </summary>
        internal static string DayNotesTitle {
            get {
                return ResourceManager.GetString("DayNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string DaySat {
            get {
                return ResourceManager.GetString("DaySat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string DaySatFull {
            get {
                return ResourceManager.GetString("DaySatFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of plan.
        /// </summary>
        internal static string DaysOfPlan {
            get {
                return ResourceManager.GetString("DaysOfPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string DaySun {
            get {
                return ResourceManager.GetString("DaySun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string DaySunFull {
            get {
                return ResourceManager.GetString("DaySunFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string DayThu {
            get {
                return ResourceManager.GetString("DayThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string DayThuFull {
            get {
                return ResourceManager.GetString("DayThuFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string DayTue {
            get {
                return ResourceManager.GetString("DayTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string DayTueFull {
            get {
                return ResourceManager.GetString("DayTueFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string DayWed {
            get {
                return ResourceManager.GetString("DayWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string DayWedFull {
            get {
                return ResourceManager.GetString("DayWedFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day &quot;{0}&quot; has {1} exercise(s). Remove it anyway? The exercises will be lost..
        /// </summary>
        internal static string DeleteDayConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteDayConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove day.
        /// </summary>
        internal static string DeleteDayConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteDayConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete plan.
        /// </summary>
        internal static string DeletePlan {
            get {
                return ResourceManager.GetString("DeletePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        internal static string DeletePlanConfirmMessage {
            get {
                return ResourceManager.GetString("DeletePlanConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete plan.
        /// </summary>
        internal static string DeletePlanConfirmTitle {
            get {
                return ResourceManager.GetString("DeletePlanConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this plan is permanent and cannot be undone..
        /// </summary>
        internal static string DeletePlanWarning {
            get {
                return ResourceManager.GetString("DeletePlanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exercises.
        /// </summary>
        internal static string ExercisesCount {
            get {
                return ResourceManager.GetString("ExercisesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercises found.
        /// </summary>
        internal static string ExercisesFound {
            get {
                return ResourceManager.GetString("ExercisesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXERCISES.
        /// </summary>
        internal static string ExercisesSectionTitle {
            get {
                return ResourceManager.GetString("ExercisesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercises.
        /// </summary>
        internal static string ExercisesShort {
            get {
                return ResourceManager.GetString("ExercisesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Type.
        /// </summary>
        internal static string ExerciseType {
            get {
                return ResourceManager.GetString("ExerciseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string FieldDistance {
            get {
                return ResourceManager.GetString("FieldDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string FieldDuration {
            get {
                return ResourceManager.GetString("FieldDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration or Distance.
        /// </summary>
        internal static string FieldDurationOrDistance {
            get {
                return ResourceManager.GetString("FieldDurationOrDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        internal static string FieldReps {
            get {
                return ResourceManager.GetString("FieldReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string FieldWeight {
            get {
                return ResourceManager.GetString("FieldWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        internal static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night.
        /// </summary>
        internal static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Bodyweight.
        /// </summary>
        internal static string IncludesBodyweight {
            get {
                return ResourceManager.GetString("IncludesBodyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises that use your body weight.
        /// </summary>
        internal static string IncludesBodyweightDesc {
            get {
                return ResourceManager.GetString("IncludesBodyweightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Remove Exercises.
        /// </summary>
        internal static string ManageExercises {
            get {
                return ResourceManager.GetString("ManageExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your weekly plans.
        /// </summary>
        internal static string ManageWeeklyPlans {
            get {
                return ResourceManager.GetString("ManageWeeklyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated 1RM.
        /// </summary>
        internal static string Metric1RM {
            get {
                return ResourceManager.GetString("Metric1RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories Burned.
        /// </summary>
        internal static string MetricCalories {
            get {
                return ResourceManager.GetString("MetricCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Distance.
        /// </summary>
        internal static string MetricDistance {
            get {
                return ResourceManager.GetString("MetricDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Progression.
        /// </summary>
        internal static string MetricDurationProgress {
            get {
                return ResourceManager.GetString("MetricDurationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Reps.
        /// </summary>
        internal static string MetricMaxReps {
            get {
                return ResourceManager.GetString("MetricMaxReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Mobility Time.
        /// </summary>
        internal static string MetricMobilityTime {
            get {
                return ResourceManager.GetString("MetricMobilityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        internal static string MetricPace {
            get {
                return ResourceManager.GetString("MetricPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reps.
        /// </summary>
        internal static string MetricTotalReps {
            get {
                return ResourceManager.GetString("MetricTotalReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string MetricTotalTime {
            get {
                return ResourceManager.GetString("MetricTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Under Tension.
        /// </summary>
        internal static string MetricTotalTUT {
            get {
                return ResourceManager.GetString("MetricTotalTUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (Weight × Reps).
        /// </summary>
        internal static string MetricVolume {
            get {
                return ResourceManager.GetString("MetricVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Consistency.
        /// </summary>
        internal static string MetricWeeklyConsistency {
            get {
                return ResourceManager.GetString("MetricWeeklyConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Progress.
        /// </summary>
        internal static string MetricWeeklyProgress {
            get {
                return ResourceManager.GetString("MetricWeeklyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight PR.
        /// </summary>
        internal static string MetricWeightPR {
            get {
                return ResourceManager.GetString("MetricWeightPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Progression.
        /// </summary>
        internal static string MetricWeightProgress {
            get {
                return ResourceManager.GetString("MetricWeightProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string MusclePrimary {
            get {
                return ResourceManager.GetString("MusclePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string MuscleSecondary {
            get {
                return ResourceManager.GetString("MuscleSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscles Involved.
        /// </summary>
        internal static string MusclesInvolved {
            get {
                return ResourceManager.GetString("MusclesInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilizer.
        /// </summary>
        internal static string MuscleStabilizer {
            get {
                return ResourceManager.GetString("MuscleStabilizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My plans.
        /// </summary>
        internal static string MyPlans {
            get {
                return ResourceManager.GetString("MyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New plan.
        /// </summary>
        internal static string NewPlan {
            get {
                return ResourceManager.GetString("NewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the name and notes for your weekly plan.
        /// </summary>
        internal static string NewPlanSubtitle {
            get {
                return ResourceManager.GetString("NewPlanSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an active plan.
        /// </summary>
        internal static string NoActivePlan {
            get {
                return ResourceManager.GetString("NoActivePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a weekly plan to start training.
        /// </summary>
        internal static string NoActivePlanSub {
            get {
                return ResourceManager.GetString("NoActivePlanSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No days configured.
        /// </summary>
        internal static string NoDaysConfigured {
            get {
                return ResourceManager.GetString("NoDaysConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No days have been configured for this plan yet..
        /// </summary>
        internal static string NoDaysConfiguredSub {
            get {
                return ResourceManager.GetString("NoDaysConfiguredSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises found.
        /// </summary>
        internal static string NoExercisesFound {
            get {
                return ResourceManager.GetString("NoExercisesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises today.
        /// </summary>
        internal static string NoExercisesToday {
            get {
                return ResourceManager.GetString("NoExercisesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active plan has no exercises assigned for today..
        /// </summary>
        internal static string NoExercisesTodaySub {
            get {
                return ResourceManager.GetString("NoExercisesTodaySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exercises yet.
        /// </summary>
        internal static string NoExercisesYet {
            get {
                return ResourceManager.GetString("NoExercisesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No muscle data available.
        /// </summary>
        internal static string NoMuscleData {
            get {
                return ResourceManager.GetString("NoMuscleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notes.
        /// </summary>
        internal static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no plans yet.
        /// </summary>
        internal static string NoPlansYet {
            get {
                return ResourceManager.GetString("NoPlansYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes (optional).
        /// </summary>
        internal static string NotesOptional {
            get {
                return ResourceManager.GetString("NotesOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description, goals, notes....
        /// </summary>
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes saved.
        /// </summary>
        internal static string NotesSaved {
            get {
                return ResourceManager.GetString("NotesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of your weight.
        /// </summary>
        internal static string OfYourWeight {
            get {
                return ResourceManager.GetString("OfYourWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan activated!.
        /// </summary>
        internal static string PlanActivated {
            get {
                return ResourceManager.GetString("PlanActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan active.
        /// </summary>
        internal static string PlanActive {
            get {
                return ResourceManager.GetString("PlanActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan detail.
        /// </summary>
        internal static string PlanDetailTitle {
            get {
                return ResourceManager.GetString("PlanDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan information.
        /// </summary>
        internal static string PlanInfoSection {
            get {
                return ResourceManager.GetString("PlanInfoSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan name.
        /// </summary>
        internal static string PlanName {
            get {
                return ResourceManager.GetString("PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. Strength 5 days.
        /// </summary>
        internal static string PlanNamePlaceholder {
            get {
                return ResourceManager.GetString("PlanNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan notes (optional).
        /// </summary>
        internal static string PlanNotesPlaceholder {
            get {
                return ResourceManager.GetString("PlanNotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan updated.
        /// </summary>
        internal static string PlanUpdated {
            get {
                return ResourceManager.GetString("PlanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Weight.
        /// </summary>
        internal static string ProfileBodyWeightLabel {
            get {
                return ResourceManager.GetString("ProfileBodyWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used as snapshot when you start a workout.
        /// </summary>
        internal static string ProfileBodyWeightSub {
            get {
                return ResourceManager.GetString("ProfileBodyWeightSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string ProfileDarkModeLabel {
            get {
                return ResourceManager.GetString("ProfileDarkModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override system theme.
        /// </summary>
        internal static string ProfileDarkModeSub {
            get {
                return ResourceManager.GetString("ProfileDarkModeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load profile..
        /// </summary>
        internal static string ProfileErrorLoad {
            get {
                return ResourceManager.GetString("ProfileErrorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings..
        /// </summary>
        internal static string ProfileErrorSave {
            get {
                return ResourceManager.GetString("ProfileErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ProfileLanguageLabel {
            get {
                return ResourceManager.GetString("ProfileLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App display language.
        /// </summary>
        internal static string ProfileLanguageSub {
            get {
                return ResourceManager.GetString("ProfileLanguageSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string ProfileLogout {
            get {
                return ResourceManager.GetString("ProfileLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving….
        /// </summary>
        internal static string ProfileSavingButton {
            get {
                return ResourceManager.GetString("ProfileSavingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY &amp; FITNESS.
        /// </summary>
        internal static string ProfileSectionBodyFitness {
            get {
                return ResourceManager.GetString("ProfileSectionBodyFitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERENCES.
        /// </summary>
        internal static string ProfileSectionPreferences {
            get {
                return ResourceManager.GetString("ProfileSectionPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string ProfileSettingsSaved {
            get {
                return ResourceManager.GetString("ProfileSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string ProfileTimezoneLabel {
            get {
                return ResourceManager.GetString("ProfileTimezoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For scheduling workouts.
        /// </summary>
        internal static string ProfileTimezoneSub {
            get {
                return ResourceManager.GetString("ProfileTimezoneSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Unit.
        /// </summary>
        internal static string ProfileWeightUnitLabel {
            get {
                return ResourceManager.GetString("ProfileWeightUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reps.
        /// </summary>
        internal static string Reps {
            get {
                return ResourceManager.GetString("Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is a rest day.
        /// </summary>
        internal static string RestDay {
            get {
                return ResourceManager.GetString("RestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest and recover energy for tomorrow.
        /// </summary>
        internal static string RestDaySub {
            get {
                return ResourceManager.GetString("RestDaySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save notes.
        /// </summary>
        internal static string SaveNotes {
            get {
                return ResourceManager.GetString("SaveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search exercises....
        /// </summary>
        internal static string SearchExercises {
            get {
                return ResourceManager.GetString("SearchExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets.
        /// </summary>
        internal static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Workout.
        /// </summary>
        internal static string StartWorkout {
            get {
                return ResourceManager.GetString("StartWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string TabExercises {
            get {
                return ResourceManager.GetString("TabExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string TabPlans {
            get {
                return ResourceManager.GetString("TabPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string TabStats {
            get {
                return ResourceManager.GetString("TabStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string TabWorkout {
            get {
                return ResourceManager.GetString("TabWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing, you agree to our Terms of Service and Privacy Policy..
        /// </summary>
        internal static string TermsAgreement {
            get {
                return ResourceManager.GetString("TermsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s plan.
        /// </summary>
        internal static string TodayPlanCaption {
            get {
                return ResourceManager.GetString("TodayPlanCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training days.
        /// </summary>
        internal static string TrainingDays {
            get {
                return ResourceManager.GetString("TrainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the days you train. If a day has exercises, confirmation will be required before removing it..
        /// </summary>
        internal static string TrainingDaysHint {
            get {
                return ResourceManager.GetString("TrainingDaysHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adjusting your filters.
        /// </summary>
        internal static string TryOtherFilters {
            get {
                return ResourceManager.GetString("TryOtherFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyweight.
        /// </summary>
        internal static string TypeBodyweightStrength {
            get {
                return ResourceManager.GetString("TypeBodyweightStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        internal static string TypeCardio {
            get {
                return ResourceManager.GetString("TypeCardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometric.
        /// </summary>
        internal static string TypeIsometric {
            get {
                return ResourceManager.GetString("TypeIsometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        internal static string TypeMobility {
            get {
                return ResourceManager.GetString("TypeMobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps Only.
        /// </summary>
        internal static string TypeRepetitionOnly {
            get {
                return ResourceManager.GetString("TypeRepetitionOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        internal static string TypeWeightedStrength {
            get {
                return ResourceManager.GetString("TypeWeightedStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Plan.
        /// </summary>
        internal static string Weekly_Plan {
            get {
                return ResourceManager.GetString("Weekly Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
